### ISSUE TITLE
获取活动接口500

### ISSUE THREAD

**Issue by zengyun-hacker** [XinranReadingGroup/XinRanLibraryManagementSystem#11]
http://www.xinrandushuba.com/mobile/activities?accessToken=60j60r2iNJ&pageNo=1&pageSize=10000&status=available

不知道是不是打开方式错误，mobile上这个接口500

**Comment by vavi** [comment]
非admin账号登录,系统页面显示异常

**Comment by gsymons** [comment]
没有判NPE以及sql写错
