### ISSUE TITLE
[web端]book detail 问题

### ISSUE THREAD

**Issue by qubaomingg** [XinranReadingGroup/XinRanLibraryManagementSystem#3]
1.  共享时间格式化 
2. 当前书状态, "共享",  "被借", xx
3. 出版年、装帧等
4. 借阅历史

好了回复下，我在调试通detail.

谢谢

**Comment by vavi** [comment]
1.$date.format($bookDetail.onOffStockRecord.createdAt) 日期格式化
2.borrow_status UNBORROWED(0), BORROWED(1) book_type DONATED(0), SHARED(1);
3. 暂不修复,见issue 1 
4. 见 $bookDetail.histroicBorrowedRecordList 字段
