### ISSUE TITLE
对于随便输入的ISBN号，不会判断错误

### ISSUE THREAD

**Issue by zengyun-hacker** [XinranReadingGroup/XinRanLibraryManagementSystem#6]
对于随便输入的一个ISBN号，比如这个
http://xinrandushuba.com/mobile/book/isbn/9781111111113 

服务器肯定没有这条的记录，但是还是会成功返回书籍信息，只不过书籍信息都是空。
建议服务端返回非200的错误码，比如404 =。=

**Comment by vavi** [comment]
已修复,增加非法参数判断.
