### ISSUE TITLE
sign接口中除了返回accessToken还可以返回用户信息

### ISSUE THREAD

**Issue by zengyun-hacker** [XinranReadingGroup/XinRanLibraryManagementSystem#7]
用户登录之后必然要获取用户信息，如果在登录成功之后顺便返回用户信息可以少发送一次请求。
http://xinrandushuba.com/mobile/user/signIn?password=5&userIdentifier=5

**Comment by vavi** [comment]
职责尽量独立吧. 通常来讲,登录后页面会重定向. 在新的页面中会具体查询用户的信息.

**Comment by zengyun-hacker** [comment]
噗。客户端客户端这边如果在重定向的页面请求用户数据，页面要空白好长一段时间，用户体验比较不好。所以合并到一个请求对于用户来说是比较好的做法。
