### ISSUE TITLE
捐书写入db永远为空

### ISSUE THREAD

**Issue by gsymons** [XinranReadingGroup/XinRanLibraryManagementSystem#8]
book = convertDouBanData2Book(douBanData);
                try{
                    synchronized(this){
                        book = bookMapper.findByISBN(isbn);
                        if(null ==book){
                            bookMapper.add(book);
                        }

```
                }
            }catch(Exception e){
                LOG.error("Error to add book to db", e);
            }
```

**Comment by vavi** [comment]
已修复,
